version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "8080:80"
    links:
      - nodejs
  nodejs:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=game
    ports:
      - "8081:8080"
  db:
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"

volumes:
  data-volume: